version: "3.5"

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    command:
      - server
      - /data

  redis:
    image: bitnami/redis:6.0
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
